---
- name: Purge Disk space
  hosts: web
  gather_facts: false 
  tasks:
  - name: Define files older than 7 days in dir "{{ mountpoint }}"
    find:
      paths: "{{ mountpoint }}"
      age: 7d
    register: files_to_delete

  - name: Purge files older than 7 days in "{{ mountpoint }}"
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"
    
  - name: gather facts
    setup:

  - name: Check Mount usage is now under 80%
    assert:
      that:
          - item.mount != mountpoint or {{ item.mount == mountpoint and item.size_available > (item.size_total|float * 0.8) }}
    with_items: "{{ ansible_mounts }}"
    ignore_errors: yes
    register: disk_free

  - name: Fixed
    debug:
      msg: "Ansible received and resolved an alert to clean up {{ mountpoint }} on {{ inventory_hostname }}."
    when: disk_free is succeeded

  - name: Not Fixed
    fail:
      msg: "Ansible received an alert to clean up {{ mountpoint }} on {{ inventory_hostname }}. However; after purging files older than 7 days old the disk is still saturated please investigate."
    when: disk_free is failed
